# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

"""Synapse package is used to interact with Synapse instance."""

# Exporting methods to be used for another modules
from .workload import (  # noqa: F401
    CHECK_ALIVE_NAME,
    CHECK_NGINX_READY_NAME,
    CHECK_READY_NAME,
    COMMAND_MIGRATE_CONFIG,
    MODERATION_CONFIG_PATH,
    STATS_EXPORTER_PORT,
    SYNAPSE_COMMAND_PATH,
    SYNAPSE_CONFIG_DIR,
    SYNAPSE_CONFIG_PATH,
    SYNAPSE_CONTAINER_NAME,
    SYNAPSE_CRON_SERVICE_NAME,
    SYNAPSE_DATA_DIR,
    SYNAPSE_DB_RELATION_NAME,
    SYNAPSE_EXPORTER_PORT,
    SYNAPSE_FEDERATION_SENDER_SERVICE_NAME,
    SYNAPSE_GROUP,
    SYNAPSE_NGINX_PORT,
    SYNAPSE_NGINX_SERVICE_NAME,
    SYNAPSE_PEER_RELATION_NAME,
    SYNAPSE_PORT,
    SYNAPSE_SERVICE_NAME,
    SYNAPSE_URL,
    SYNAPSE_USER,
    SYNAPSE_WORKER_CONFIG_PATH,
    ExecResult,
    WorkloadError,
    create_registration_secrets_files,
    execute_migrate_config,
    generate_moderation_config,
    generate_nginx_config,
    generate_worker_config,
    get_environment,
    get_media_store_path,
    get_registration_shared_secret,
    run_media_sync_cleanup,
    validate_config,
)
from .workload_configuration import (  # noqa: F401
    add_default_configurations,
    block_non_admin_invites,
    configure_mas,
    disable_room_list_search,
    enable_allow_public_rooms_over_federation,
    enable_background_tasks_worker,
    enable_federation_domain_whitelist,
    enable_federation_sender,
    enable_instance_map,
    enable_ip_range_whitelist,
    enable_limit_remote_rooms_complexity,
    enable_media,
    enable_redis,
    enable_registration_secrets,
    enable_room_list_publication_rules,
    enable_smtp,
    enable_stream_writers,
    enable_synapse_invite_checker,
    enable_trusted_key_servers,
    set_public_baseurl,
    set_rate_limiting_level,
)
