ignore_files:
  - lib/charms/nginx_ingress_integrator/v0/nginx_route.py
  - pyproject.toml
  - src/grafana_dashboards/synapse.json
  - tests/unit/test_synapse_workload.py
  - docs/reference/integrations.md
rules:
  # Ignore "master" - While https://github.com/canonical/redis-k8s-operator/pull/78
  # is not merged
  - name: master
  # Ignore "grandfathered" used by SAML configuration.
  - name: grandfathered
  # Ignore "whitelist" used by Synapse configuration.
  - name: whitelist
