# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  allow_public_rooms_over_federation:
    type: boolean
    default: false
    description: |
      Allows any other homeserver to fetch the server's public rooms directory
      via federation.
  backup_passphrase:
    type: string
    description: Passphrase used to encrypt a backup using gpg with symmetric key.
  enable_email_notifs:
    type: boolean
    default: false
    description: |
      Configures whether to enable e-mail notifications. Requires SMTP integration.
  enable_mjolnir:
    type: boolean
    default: false
    description: |
      Configures whether to enable Mjolnir - moderation tool for Matrix.
      Reference: https://github.com/matrix-org/mjolnir
  enable_password_config:
    type: boolean
    default: true
    description: |
      Defaults to true. If Synapse uses a single sign-on provider for
      authentication, this option can be used to disable the regular login
      flow.
  enable_room_list_search:
    type: boolean
    default: true
    description: |
      When disabled, blocks searching local and remote room lists for local and
      remote users by always returning an empty list for all queries.
  federation_domain_whitelist:
    type: string
    description: Comma separated list of domains to be allowed to federate.
  ip_range_whitelist:
    type: string
    description: |
      Comma separated list of IP address CIDR ranges that should be allowed for
      federation, identity servers, push servers, and for checking key validity
      for third-party invite events.
  invite_checker_blocklist_allowlist_url:
    type: string
    description: URL to fetch the JSON file containing the allowlist and
      blocklist.
  invite_checker_policy_rooms:
    type: string
    description: |
      Comma separated list of rooms to be used by the invite checker module.
  limit_remote_rooms_complexity:
    type: float
    description: if set, the room "complexity" will be checked before a user
      joins a new remote room. If the complexity is higher, the user will not be
      able to join the room.
  notif_from:
    type: string
    description: defines the "From" address to use when sending emails.
      It must be set if the SMTP integration is enabled. Defaults to server_name.
  public_baseurl:
    type: string
    description: |
      The public-facing base URL that clients use to access this Homeserver.
      Defaults to https://<server_name>/. Only used if there is integration with
      SAML integrator charm.
  experimental_alive_check:
    type: string
    description: Comma separated list of period,threshold and timeout for Synapse
      pebble alive check. Refer to https://github.com/canonical/pebble/#layer-specification
      to more details about allowed values.
      This is an experimental feature and may be removed in future releases.
    default: "2m,5,20s"
  rc_joins_remote_burst_count:
    type: int
    description: Allows for ratelimiting number of remote rooms a user can join
      before being throttled.
    default: 10
  rc_joins_remote_per_second:
    type: float
    description: Allows for ratelimiting number of remote rooms a user can join
      per second.
    default: 0.01
  report_stats:
    description: |
      Configures whether to report statistics.
    default: false
    type: boolean
  publish_rooms_allowlist:
      type: string
      description: |
        Comma separated list of users allowed to publish rooms. Once is set, no
        other users will be allowed to publish rooms.
        This takes the form of user1:domainX.com,user2:domainY.com...
  server_name:
    type: string
    description: |
      Synapse server name. Must be set to deploy the charm. Corresponds to the
      server_name option on Synapse configuration file and sets the
      public-facing domain of the server.
  trusted_key_servers:
    type: string
    description: Comma separated list of trusted servers to download signing
      keys from. Synapse configuration sets default to matrix.org.
  workers_ignore_list:
    type: string
    description: Comma separated list of workers that should be ignored while
      setting instance_map and stream writers. This configuration should be used
      in case of unrecoverable broken units and takes the form of
      worker0,worker1
