# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  allow_public_rooms_over_federation:
    type: boolean
    default: false
    description: |
      Allows any other homeserver to fetch the server's public rooms directory
      via federation.
  enable_mjolnir:
    type: boolean
    default: false
    description: |
      Configures whether to enable Mjolnir - moderation tool for Matrix.
      Reference: https://github.com/matrix-org/mjolnir
  enable_password_config:
    type: boolean
    default: true
    description: |
      Defaults to true. If Synapse uses a single sign-on provider for
      authentication, this option can be used to disable the regular login
      flow.
  enable_room_list_search:
    type: boolean
    default: true
    description: |
      When disabled, blocks searching local and remote room lists for local and
      remote users by always returning an empty list for all queries.
  federation_domain_whitelist:
    type: string
    description: Comma separated list of domains to be allowed to federate.
  ip_range_whitelist:
    type: string
    description: |
      Comma separated list of IP address CIDR ranges that should be allowed for
      federation, identity servers, push servers, and for checking key validity
      for third-party invite events.
  notif_from:
    type: string
    description: defines the "From" address to use when sending emails.
      It must be set if email sending is enabled. Defaults to server_name.
  public_baseurl:
    type: string
    description: |
      The public-facing base URL that clients use to access this Homeserver.
      Defaults to https://<server_name>/. Only used if there is integration with
      SAML integrator charm.
  report_stats:
    description: |
      Configures whether to report statistics.
    default: false
    type: boolean
  server_name:
    type: string
    description: |
      Synapse server name. Must be set to deploy the charm. Corresponds to the
      server_name option on Synapse configuration file and sets the
      public-facing domain of the server.
  trusted_key_servers:
    type: string
    description: Comma separated list of trusted servers to download signing
      keys from. Synapse configuration sets default to matrix.org.
