# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  server_name:
    type: string
    description: |
      Synapse server name. Must be set to deploy the charm. Corresponds to the
      server_name option on Synapse configuration file.
    default: ""
  report_stats:
    description: |
      Configures whether to report statistics.

      Acceptable values are: "yes" and "no"
    default: "no"
    type: string
