# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  server_name:
    type: string
    description: |
      Synapse server name. Must be set to deploy the charm. Corresponds to the
      server_name option on Synapse configuration file and sets the
      public-facing domain of the server.
  report_stats:
    description: |
      Configures whether to report statistics.
    default: false
    type: boolean
  public_baseurl:
    type: string
    description: |
      The public-facing base URL that clients use to access this Homeserver.
      Defaults to https://<server_name>/. Only used if there is integration with
      SAML integrator charm.
  enable_mjolnir:
    type: boolean
    default: false
    description: |
      Configures whether to enable Mjolnir - moderation tool for Matrix.
      Reference: https://github.com/matrix-org/mjolnir
  delegation_server_name:
    type: string
    description: |
      Delegation server name. If set, a .well-known/matrix/server file will be
      created using this configuration as value to the key m.server. Example:
      synapse.example.com:443
      Reference: https://matrix-org.github.io/synapse/latest/delegate.html
    default: ""
