{
 "title": "Synapse Operator",
 "tags": [ "matrix" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "lokids", "label": "Loki datasource", "query": "loki" },
   { "name": "prometheusds", "label": "Prometheus datasource", "query": "prometheus" },
   {
    "name": "juju_unit",
    "label": "Juju unit",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_application=~\"$juju_application\"},juju_unit)"
    }
   },
   {
    "name": "juju_application",
    "label": "Juju application",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\"},juju_application)"
    }
   },
   {
    "name": "juju_model_uuid",
    "label": "Juju model uuid",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\"},juju_model_uuid)"
    }
   },
   { "name": "juju_model", "label": "Juju model", "query": { "query": "label_values(up,juju_model)" } },
   { "name": "bucket_size", "label": "Bucket Size", "query": "30s,1m,2m,5m,10m,15m" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(synapse_util_metrics_block_ru_utime_seconds_total, instance)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(synapse_util_metrics_block_ru_utime_seconds_total, job)"
    }
   },
   {
    "name": "index",
    "query": {
     "query": "label_values(synapse_util_metrics_block_ru_utime_seconds_total, index)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "[Events] Traffic",
   "type": "timeseries",
   "description": "Total number of requests per minute over the last 5 minutes.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum(rate(synapse_http_server_responses_total{juju_model=~\"$juju_model\"}[5m])*60)\n",
     "legendFormat": "Requests/min"
    }
   ]
  },
  {
   "title": "[Federation] Incoming PDU/EDU rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "sum(rate(synapse_federation_server_received_pdus_total{instance=~\"$instance\"}[$bucket_size]))",
     "legendFormat": "pdus"
    },
    {
     "expr": "sum(rate(synapse_federation_server_received_edus_total{instance=~\"$instance\"}[$bucket_size]))",
     "legendFormat": "edus"
    }
   ]
  },
  {
   "title": "[System] CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\".*synapse_application.*\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$bucket_size])",
     "legendFormat": "{{job}}-{{index}} "
    }
   ]
  },
  {
   "title": "[System] Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jemalloc_stats_app_memory_bytes{juju_application=\"synapse\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",type=\"mapped\"}",
     "legendFormat": "{{job}} {{index}}"
    }
   ]
  },
  {
   "title": "[System] GC frequency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "rate(python_gc_time_count{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
     "legendFormat": "{{job}}-{{index}} gen {{gen}}"
    }
   ]
  },
  {
   "title": "[System] Open FDs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_open_fds{index=~\"$index\",instance=\"$instance\",job=~\"$job\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "{{job}}-{{index}}"
    }
   ]
  },
  {
   "title": "Event persistence",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Events/s Local vs Remote",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_storage_events_persisted_by_source_type{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Events Persisted (all workers)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "sum(rate(synapse_storage_events_persisted_events_total{instance=\"$instance\"}[$bucket_size])) without (job,index)"
      }
     ]
    },
    {
     "title": "Events/s by Origin",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_storage_events_persisted_by_origin{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{origin_entity}} ({{origin_type}})"
      }
     ]
    },
    {
     "title": "Events/s by Type",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_storage_events_persisted_by_event_type{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Background jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU usage by background jobs",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_background_process_ru_utime_seconds_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])+rate(synapse_background_process_ru_stime_seconds_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{name}}"
      }
     ]
    },
    {
     "title": "DB usage by background jobs (including scheduling time)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_background_process_db_txn_duration_seconds_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]) +  rate(synapse_background_process_db_sched_duration_seconds_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{name}}"
      }
     ]
    },
    {
     "title": "Background jobs in flight",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "synapse_background_process_in_flight_count{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}",
       "legendFormat": "{{job}}-{{index}} {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Avg time waiting for db conn",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(synapse_storage_schedule_time_sum{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])/rate(synapse_storage_schedule_time_count[$bucket_size])",
       "legendFormat": "{{job}}-{{index}}"
      }
     ]
    },
    {
     "title": "Db scheduling time quantiles",
     "type": "graph",
     "description": "Shows the time in which the given percentage of database queries were scheduled, over the sampled timespan",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(synapse_storage_schedule_time_bucket{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]))",
       "legendFormat": "{{job}} {{index}} 99%"
      },
      {
       "expr": "histogram_quantile(0.95, rate(synapse_storage_schedule_time_bucket{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]))",
       "legendFormat": "{{job}} {{index}} 95%"
      },
      {
       "expr": "histogram_quantile(0.90, rate(synapse_storage_schedule_time_bucket{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]))",
       "legendFormat": "{{job}} {{index}} 90%"
      },
      {
       "expr": "rate(synapse_storage_schedule_time_sum{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])/rate(synapse_storage_schedule_time_count{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}} {{index}} mean"
      }
     ]
    },
    {
     "title": "Top DB transactions by txn rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "topk(10, rate(synapse_storage_transaction_time_count_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]))",
       "legendFormat": "{{job}}-{{index}} {{desc}}"
      }
     ]
    },
    {
     "title": "Average DB txn time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_storage_transaction_time_sum_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])/rate(synapse_storage_transaction_time_count_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{desc}}"
      }
     ]
    }
   ]
  }
 ]
}