{
 "title": "Synapse Service Health",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheusds", "query": "prometheus" },
   { "name": "synapse_model", "query": { "query": "label_values(juju_model)" } }
  ]
 },
 "panels": [
  {
   "title": "LATENCY",
   "type": "timeseries",
   "description": "95% of requests were completed in this time or less.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(synapse_http_server_response_time_seconds_bucket{code=~\"2..\", juju_model=~\"$synapse_model\"}[5m])) by (le))",
     "legendFormat": "OK"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(synapse_http_server_response_time_seconds_bucket{code!~\"2..\",juju_model=~\"$synapse_model\"}[5m])) by (le))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "ERRORS",
   "type": "timeseries",
   "description": "Current rate of failed requests per minute, based on the last 5 minutes, grouped by error code.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by(code) (rate(synapse_http_server_responses_total{code=~\"5..\", juju_model=~\"$synapse_model\"}[5m]) * 60)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TRAFFIC",
   "type": "timeseries",
   "description": "Total number of requests per minute over the last 5 minutes.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum(rate(synapse_http_server_responses_total{juju_model=~\"$synapse_model\"}[5m])*60)\n",
     "legendFormat": "Requests/min"
    }
   ]
  },
  {
   "title": "SATURATION",
   "type": "timeseries",
   "description": "CPU and memory usage of the most resource-consuming unit over the last 5 minutes.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "max(rate(process_cpu_seconds_total{juju_unit=~\"synapse.*\",job=~\".*synapse_application.*\", juju_model=~\"$synapse_model\"}[2m]))",
     "legendFormat": "CPU {{juju_unit}}"
    },
    {
     "expr": "max(jemalloc_stats_app_memory_bytes{juju_unit=~\"synapse.*\",job=~\".*synapse_application.*\",juju_model=~\"$synapse_model\"})",
     "legendFormat": "Memory {{juju_unit}}"
    }
   ]
  }
 ]
}