@startuml MAS high-availability deployment
node leader{
  [synapse-main] as sl
  [mas-server] as ml
  [mas-worker] as mlw
  [nginx] as nl
  () "::8080" as il
  sl -down[hidden]- mlw
  ml -right[hidden]- nl
  ml -left- mlw
  il -left- nl
}

node worker{
  [synapse-worker] as sw
  [mas-worker] as mw
  [nginx] as nw
  () "::8080" as iw
  sw -up[hidden]- mw
  mw -right[hidden]- nw: xxx
  iw -left- nw
}

Actor User

il <---down- User: HTTP
User -left-> iw: HTTP

nl -left-> ml: ^/_matrix/client/(.*)/(login|logout|refresh), /auth
nw -up-> ml: ^/_matrix/client/(.*)/(login|logout|refresh), /auth

database "postgresql-mas" as p
mw -up- p
mlw -down- p
@enduml
