name: Auto-update charm libraries

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  auto-update-libs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: track/1 

      - name: Run charm library auto-update
        uses: canonical/operator-workflows/.github/workflows/auto_update_charm_libs.yaml@main
        secrets: inherit
