name: Auto-merge PR

on:
  pull_request_target:

jobs:
  automerge:
    name: Auto-merge
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.head.ref, 'renovate')
    steps:
      - uses: alexwilson/enable-github-automerge-action@2.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          merge-method: "SQUASH"
