name: Integration tests (require secrets)

on:
  pull_request:

jobs:
  integration-tests-with-secrets:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      chaos-app-label: app.kubernetes.io/name=synapse
      chaos-enabled: false
      chaos-experiments: pod-delete
      extra-arguments: -m "requires_secrets"
      trivy-image-config: "trivy.yaml"
      self-hosted-runner: true
      self-hosted-runner-label: "edge"
      juju-channel: 3.1/stable
      channel: 1.28-strict/stable
