name: Integration tests

on:
  pull_request:

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      run_tests: ${{ steps.set-output.outputs.run_tests }}
    steps:
      - uses: actions/checkout@v4

      - uses: tj-actions/changed-files@v46.0.5
        id: changed-files

      - name: Set output if non-terraform files changed
        id: set-output
        run: |
          echo "run_tests=false" >> "$GITHUB_OUTPUT"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ "$file" != terraform/* ]]; then
              echo "run_tests=true" >> "$GITHUB_OUTPUT"
              break
            fi
          done

  integration-tests:
    if: needs.check-changes.outputs.run_tests == 'true'
    needs: check-changes
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      extra-arguments: -x --localstack-address 172.17.0.1
      pre-run-script: localstack-installation.sh
      trivy-image-config: "trivy.yaml"
      juju-channel: 3.6/stable
      channel: 1.32-classic/stable
      use-canonical-k8s: true
      extra-arguments: |
        --kube-config=~/.kube/config
      provider: 'k8s'
      modules: '["test_charm", "test_nginx", "test_s3", "test_scaling", "test_matrix_auth"]'
