name: Integration tests

on:
  pull_request:

jobs:
  integration-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      extra-arguments: -x --localstack-address 172.17.0.1
      pre-run-script: localstack-installation.sh
      trivy-image-config: "trivy.yaml"
      extra-arguments: |
        --kube-config=~/.kube/config
      modules: '["test_charm", "test_nginx", "test_s3", "test_scaling"]'
      channel: 1.34-classic/stable
      juju-channel: 3.6/stable
      self-hosted-runner: true
      self-hosted-runner-label: "xlarge"
      use-canonical-k8s: true
      provider: 'k8s'
