name: Integration tests

on:
  pull_request:

jobs:
  integration-tests:
    name: Integration test with juju 3.1
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      extra-arguments: -x
      trivy-image-config: "trivy.yaml"
      juju-channel: 3.1/stable
      channel: 1.28-strict/stable
      modules: '["test_charm", "test-mjolnir", "test_nginx", "test_cos"]'
  integration-tests-s3:
    name: Integration test with juju 3.1
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      extra-arguments: -x --localstack-address 172.17.0.1
      pre-run-script: localstack-installation.sh
      trivy-image-config: "trivy.yaml"
      juju-channel: 3.1/stable
      channel: 1.28-strict/stable
      modules: '["test_s3"]'
