name: Publish to edge

on:
  workflow_dispatch:
  push:
    branches:
      - 2/main

jobs:
  publish-to-edge:
    uses: canonical/operator-workflows/.github/workflows/publish_charm.yaml@main
    secrets: inherit
    with:
      channel: 2/edge
