name: Publish to edge

on:
  push:
    branches:
      - track/1

jobs:
  publish-to-edge:
    uses: canonical/operator-workflows/.github/workflows/publish_charm.yaml@main
    permissions:
      contents: read
      packages: write
    secrets: inherit
    with:
      channel: 1/edge
