name: Integration tests

on:
  schedule:
    # Trigger at 6:00 AM and 6:00 PM UTC
    - cron: "0 6,18 * * *"

jobs:
  integration-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      extra-arguments: -x --localstack-address 172.17.0.1
      pre-run-script: localstack-installation.sh
      trivy-image-config: "trivy.yaml"
      juju-channel: 3.6/stable
      channel: 1.28-strict/stable
      modules: '["test_charm", "test_nginx", "test_s3", "test_scaling", "test_matrix_auth"]'
  allure-report:
    if: ${{ (success() || failure()) && github.event_name == 'schedule' }}
    needs:
      - integration-tests
    uses: canonical/operator-workflows/.github/workflows/allure_report.yaml@main
