name: Tests

on:
  pull_request_target:
    types:
      - opened
      - reopened
    branches:
      - '2/main'

jobs:
  unit-tests:
    uses: canonical/operator-workflows/.github/workflows/test.yaml@swetha1654-patch-vale
    secrets: inherit
    with:
      self-hosted-runner: false
      self-hosted-runner-label: "edge"
      vale-style-check: false
