name: Test trivy ignore

on:
  workflow_call:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build Rock
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      rock-image-url: ${{ steps.image_url.outputs.ghcr_image_url }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup LXD
        if: false
        uses: canonical/setup-lxd@main

      - name: Install required dependencies
        if: false
        run: |
          # rockcraft
          sudo snap install rockcraft --classic
      - name: Build rock
        if: false
        run: |
          cd synapse_rock
          rockcraft pack --verbose
      - name: Set image URL
        id: image_url
        run: |
          # IMAGE_URL=ghcr.io/${{ github.repository }}:$(date +%s)-${GITHUB_SHA:0:7}
          IMAGE_URL=ghcr.io/canonical/synapse-operator:1755116210-af837ee
          echo "ghcr_image_url=$IMAGE_URL" >> $GITHUB_OUTPUT
          echo "image_url=$IMAGE_URL" >> $GITHUB_OUTPUT
      - name: Push Rock to GHCR
        if: false
        run: |
          cd synapse_rock
          rockcraft.skopeo --insecure-policy copy \
            oci-archive:$(ls *.rock) \
            docker://${{ steps.image_url.outputs.ghcr_image_url }} \
            --dest-creds "canonical:${{ secrets.GITHUB_TOKEN }}"

  test:
     runs-on: ubuntu-latest
     needs: build
     if: ${{ needs.build.outputs.rock-image-url != '' }}
     name: Check unused entries in .trivyignore
     steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Run trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
            | sh -s -- -b /usr/local/bin

          if [ -f ".trivyignore" ]; then
            # Get ignored CVEs from Trivy
            ignored_cves=$(trivy image "$ROCK_IMAGE" \
              --severity "CRITICAL,HIGH" \
              --show-suppressed \
              -q -f json \
              | jq -r '.Results[].ExperimentalModifiedFindings[]? 
                      | select(.Status == "ignored") 
                      | .Finding.VulnerabilityID' \
              | sort -u)

            all_cves=$(trivy image "$ROCK_IMAGE" \
            --severity "CRITICAL,HIGH" \
            --show-suppressed \
            -q -f json \
            | jq -r '.Results[].Vulnerabilities // [] | .[].VulnerabilityID') > all_cves.txt

            # Loop through .trivyignore and check if each CVE is still ignored
            line=0
            while read -r CVE; do
              line=$(( line + 1 ))
              [[ "$CVE" =~ ^#.*$ || -z "$CVE" ]] && continue
              if ! grep -q -F "$CVE" <<< "$ignored_cves"; then
                echo "$CVE" >> unused_cves.txt
              fi
            done < .trivyignore

            # If unused CVEs found, post PR comment
            if [ -s unused_cves.txt ]; then
              {
                echo "### CVEs"
                cat all_cves.txt | sed 's/^/- /'
                echo "### 🧹 Unused entries in .trivyignore"
                echo ""
                echo "The following CVEs are in \`.trivyignore\` but not ignored by Trivy anymore:"
                echo ""
                cat unused_cves.txt | sed 's/^/- /'
              } > pr_comment.md

              gh pr comment ${{ github.event.number }} --repo ${{ github.repository }} --body-file pr_comment.md || true
            fi
          else
            echo "::warning::File .trivyignore not found."
          fi
        env:
          TRIVY_USERNAME: ${{ github.actor }}
          TRIVY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          ROCK_IMAGE: "${{ needs.build.outputs.rock-image-url }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
