name: Publish to edge

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-to-edge:
    uses: canonical/operator-workflows/.github/workflows/test_and_publish_charm.yaml@main
    secrets: inherit
    with:
      trivy-image-config: "trivy.yaml"
